# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-07 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0002_auto_20161007_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oldhouse',
            name='houseId',
        ),
        migrations.AlterField(
            model_name='oldhouse',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
