# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-07 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0003_auto_20161007_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='oldhouse',
            name='follow',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='oldhouse',
            name='publishBefore',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='oldhouse',
            name='visit',
            field=models.IntegerField(null=True),
        ),
    ]
