# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-07 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0004_auto_20161007_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='oldhouse',
            name='area',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
